### ISSUE TITLE
Keep getting `already borrowed: BorrowMutError`. Guidelines on troubleshooting

### ISSUE THREAD

**Issue by sebasmagri** [al8n/stretto#10]
I've been trying to troubleshoot some panics using stretto-0.3.3 mapping to `stretto::cache::axync::AsyncCache::insert_with_ttl` and I think panicking at [this point](https://github.com/al8n/stretto/blob/main/src/ttl.rs#L140) with the message: `already borrowed: BorrowMutError`.

I've increased my counters and it seems to have helped, but still get it pretty often.

Any guidance on how to troubleshoot this?

**Comment by sebasmagri** [comment]
Adding a full backtrace as support:
```
thread 'rocket-worker-thread' panicked at 'already borrowed: BorrowMutError', /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/stretto-0.3.3/src/ttl.rs:166:23
stack backtrace:
   0:     0x7fb495d4088d - std::backtrace_rs::backtrace::libunwind::trace::h9950907a6040bcea
                               at /rustc/3c17c84a386e7badf6b2c6018d172496b3a28a04/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7fb495d4088d - std::backtrace_rs::backtrace::trace_unsynchronized::h58f3f39ababcbdf8
                               at /rustc/3c17c84a386e7badf6b2c6018d172496b3a28a04/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7fb495d4088d - std::sys_common::backtrace::_print_fmt::hd3e03652b926f65b
                               at /rustc/3c17c84a386e7badf6b2c6018d172496b3a28a04/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x7fb495d4088d - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h4649f32e4df82b54
                               at /rustc/3c17c84a386e7badf6b2c6018d172496b3a28a04/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x7fb495db86ac - core::fmt::write::h67f6aa66aced9104
                               at /rustc/3c17c84a386e7badf6b2c6018d172496b3a28a04/library/core/src/fmt/mod.rs:1190:17
   5:     0x7fb495d31e81 - std::io::Write::write_fmt::hec4693c37aac724f
                               at /rustc/3c17c84a386e7badf6b2c6018d172496b3a28a04/library/std/src/io/mod.rs:1655:15
   6:     0x7fb495d43975 - std::sys_common::backtrace::_print::h338d0a2b0d710eba
                               at /rustc/3c17c84a386e7badf6b2c6018d172496b3a28a04/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x7fb495d43975 - std::sys_common::backtrace::print::h6b39d0d10af310e1
                               at /rustc/3c17c84a386e7badf6b2c6018d172496b3a28a04/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x7fb495d43975 - std::panicking::default_hook::{{closure}}::h64b601284b1d3e33
                               at /rustc/3c17c84a386e7badf6b2c6018d172496b3a28a04/library/std/src/panicking.rs:295:22
   9:     0x7fb495d43629 - std::panicking::default_hook::h11492d08067743a3
                               at /rustc/3c17c84a386e7badf6b2c6018d172496b3a28a04/library/std/src/panicking.rs:314:9
  10:     0x7fb4942b5e49 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::hcaccd347ca5027a4
  11:     0x7fb4942b638b - <sentry_panic::PanicIntegration as sentry_core::integration::Integration>::setup::{{closure}}::{{closure}}::h4600d2d584a58bc9
  12:     0x7fb495d440c0 - std::panicking::rust_panic_with_hook::h253b9fe7078db797
                               at /rustc/3c17c84a386e7badf6b2c6018d172496b3a28a04/library/std/src/panicking.rs:702:17
  13:     0x7fb495d43ef7 - std::panicking::begin_panic_handler::{{closure}}::h4b12bb20b7f21b5c
                               at /rustc/3c17c84a386e7badf6b2c6018d172496b3a28a04/library/std/src/panicking.rs:588:13
  14:     0x7fb495d40d44 - std::sys_common::backtrace::__rust_end_short_backtrace::h8b216cb5e5002128
                               at /rustc/3c17c84a386e7badf6b2c6018d172496b3a28a04/library/std/src/sys_common/backtrace.rs:138:18
  15:     0x7fb495d43c29 - rust_begin_unwind
                               at /rustc/3c17c84a386e7badf6b2c6018d172496b3a28a04/library/std/src/panicking.rs:584:5
  16:     0x7fb493c47f63 - core::panicking::panic_fmt::h50155a72a4ea81ae
                               at /rustc/3c17c84a386e7badf6b2c6018d172496b3a28a04/library/core/src/panicking.rs:143:14
  17:     0x7fb493c48053 - core::result::unwrap_failed::h9f543abef8c6822a
                               at /rustc/3c17c84a386e7badf6b2c6018d172496b3a28a04/library/core/src/result.rs:1784:5
  18:     0x7fb494bd0376 - core::result::Result<T,E>::expect::ha35de5123d1c7ee4
  19:     0x7fb494bc853a - core::cell::RefCell<T>::borrow_mut::hb72ae6e079c5dfd3
  20:     0x7fb494bfce2b - stretto::ttl::ExpirationMap<S>::update::hc1b8c0a0c6c1b440
  21:     0x7fb493f86b9f - stretto::store::ShardedMap<V,U,SS,ES>::update::h7804406fcf37475d
  22:     0x7fb493f85282 - stretto::cache::axync::AsyncCache<K,V,KH,C,U,CB,S>::update::h22ec67ae5548ab25
  23:     0x7fb493f85972 - stretto::cache::axync::AsyncCache<K,V,KH,C,U,CB,S>::insert_in::{{closure}}::h125e898709133e51
  24:     0x7fb493fe4e3c - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hca880410c421ccb8
  25:     0x7fb493f8455d - stretto::cache::axync::AsyncCache<K,V,KH,C,U,CB,S>::insert_with_ttl::{{closure}}::hcc595a5faea93776
  26:     0x7fb493fe5adc - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hd48cbc9d3522333a
  27:     0x7fb493cd79f8 - ...::Storage::_mem_insert_with_ttl::{{closure}}::{{closure}}::h100123ee61e0dab1
  28:     0x7fb493fea281 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hff688bd2df4adc71
  29:     0x7fb493fb6435 - <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll::hf8a21e179f575450
  30:     0x7fb493cd2164 - ...::Storage::_mem_insert_with_ttl::{{closure}}::h124886cdfdba0213
  31:     0x7fb493fdcfc1 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h7c709c7b21f6e2ed
  32:     0x7fb493cebc20 - ...::Storage::query::{{closure}}::{{closure}}::h8cb6cbe1f5ad2838
  33:     0x7fb493fda971 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h699eb78b86bb4052
  34:     0x7fb493fb6165 - <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll::heeec811572bb72ce
  35:     0x7fb493cea8cb - ...::Storage::query::{{closure}}::h776bc6f3e8cae8b2
  36:     0x7fb493fea371 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hffaab3630d1b9851
  37:     0x7fb4940619a4 - ...::{{closure}}::{{closure}}::h64fe0db357c4b56c
  38:     0x7fb493fd527f - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h32de95b9cd52dd6c
  39:     0x7fb493fb2655 - <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll::h0f1992fed843ca84
  40:     0x7fb494061323 - ...::{{closure}}::hd367476a49485f3f
  41:     0x7fb493fe97ff - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hfa1a7e603da20b90
  42:     0x7fb494051962 - <... as juniper::types::async_await::GraphQLValueAsync<__S>>::resolve_field_async::{{closure}}::{{closure}}::h66fdcea921baa020
  43:     0x7fb493fe86d1 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hede2d2f54617b6e7
  44:     0x7fb494050a9d - <... as juniper::types::async_await::GraphQLValueAsync<__S>>::resolve_field_async::{{closure}}::h86d5f9517a2c779f
  45:     0x7fb493fd6711 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h422c728caa9aabd8
  46:     0x7fb493ec827a - <core::pin::Pin<P> as core::future::future::Future>::poll::hbb198bcdf12aeedd
  47:     0x7fb493f2441d - juniper::types::async_await::resolve_selection_set_into_async_recursive::{{closure}}::{{closure}}::h4f2e2fc62a36b26d
  48:     0x7fb493fd7251 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h4797a23eccb603d3
  49:     0x7fb493d30aa1 - <juniper::types::async_await::resolve_selection_set_into_async_recursive::{{closure}}::AsyncValueFuture<A,B,C,D> as core::future::future::Future>::poll::h49d57b467c9c5dea
  50:     0x7fb493c59cce - <futures_util::stream::futures_ordered::OrderWrapper<T> as core::future::future::Future>::poll::hdc28d3a5a15dcb9e
  51:     0x7fb493c7876b - <futures_util::stream::futures_unordered::FuturesUnordered<Fut> as futures_core::stream::Stream>::poll_next::he70befc7e8cd3a96
  52:     0x7fb493ca83e4 - futures_util::stream::stream::StreamExt::poll_next_unpin::hf3a712950eb6d476
  53:     0x7fb493c670b7 - <futures_util::stream::futures_ordered::FuturesOrdered<Fut> as futures_core::stream::Stream>::poll_next::h9ff31d7b7df6f8b6
  54:     0x7fb493ca7e24 - futures_util::stream::stream::StreamExt::poll_next_unpin::h39a1cdfb44ee7e49
  55:     0x7fb493feec7c - <futures_util::stream::stream::next::Next<St> as core::future::future::Future>::poll::h35a55d78bab46152
  56:     0x7fb493f0a2a2 - juniper::types::async_await::resolve_selection_set_into_async_recursive::{{closure}}::h205609eede947078
  57:     0x7fb493fe8311 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::heca2666c5cf46d6f
  58:     0x7fb493ec7eaa - <core::pin::Pin<P> as core::future::future::Future>::poll::h4c14545942c34d7e
  59:     0x7fb493f05456 - juniper::types::async_await::GraphQLValueAsync::resolve_async::{{closure}}::h284e144f012b71f8
  60:     0x7fb493fe51b1 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hccbc00896b966334
  61:     0x7fb493ec827a - <core::pin::Pin<P> as core::future::future::Future>::poll::hbb198bcdf12aeedd
  62:     0x7fb493f73cd3 - juniper::executor::Executor<CtxT,S>::resolve_async::{{closure}}::h4cd6f6991f2ac84d
  63:     0x7fb493fe7191 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::he2558c27eda319f9
  64:     0x7fb493f7f919 - juniper::executor::Executor<CtxT,S>::resolve_with_ctx_async::{{closure}}::hef05f3800991913a
  65:     0x7fb493fd1b21 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h1438133b1aec71b6
  66:     0x7fb4940c2e27 - <... as juniper::types::async_await::GraphQLValueAsync<__S>>::resolve_field_async::{{closure}}::h8bf71ccf8fb89ca3
  67:     0x7fb493fe1011 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h9e43d475b567b1e2
  68:     0x7fb493ec827a - <core::pin::Pin<P> as core::future::future::Future>::poll::hbb198bcdf12aeedd
  69:     0x7fb493f2934d - juniper::types::async_await::resolve_selection_set_into_async_recursive::{{closure}}::{{closure}}::hb6ac7a4166e288cd
  70:     0x7fb493fe38d1 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hbb03949f5e60da1d
  71:     0x7fb493d30ee1 - <juniper::types::async_await::resolve_selection_set_into_async_recursive::{{closure}}::AsyncValueFuture<A,B,C,D> as core::future::future::Future>::poll::hecda639086db1dee
  72:     0x7fb493c59b1e - <futures_util::stream::futures_ordered::OrderWrapper<T> as core::future::future::Future>::poll::haccacb1265acf8dc
  73:     0x7fb493c7a50b - <futures_util::stream::futures_unordered::FuturesUnordered<Fut> as futures_core::stream::Stream>::poll_next::hec2e6bfa67c6d27a
  74:     0x7fb493ca7ea4 - futures_util::stream::stream::StreamExt::poll_next_unpin::h3f8290f8b701fb60
  75:     0x7fb493c68237 - <futures_util::stream::futures_ordered::FuturesOrdered<Fut> as futures_core::stream::Stream>::poll_next::hd53ac7868109a090
  76:     0x7fb493ca7f24 - futures_util::stream::stream::StreamExt::poll_next_unpin::h55131ba48d9243c2
  77:     0x7fb493feeeac - <futures_util::stream::stream::next::Next<St> as core::future::future::Future>::poll::h870033c56712efaf
  78:     0x7fb493f1c362 - juniper::types::async_await::resolve_selection_set_into_async_recursive::{{closure}}::hd70587f98c803e79
  79:     0x7fb493fd9271 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h5f43ab4ed7142ac4
  80:     0x7fb493ec7eaa - <core::pin::Pin<P> as core::future::future::Future>::poll::h4c14545942c34d7e
  81:     0x7fb493f06306 - juniper::types::async_await::GraphQLValueAsync::resolve_async::{{closure}}::h9eb63a44ce3178c6
  82:     0x7fb493fe5661 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hd075dbd6f96a8c99
  83:     0x7fb493ec827a - <core::pin::Pin<P> as core::future::future::Future>::poll::hbb198bcdf12aeedd
  84:     0x7fb493f739c3 - juniper::executor::Executor<CtxT,S>::resolve_async::{{closure}}::h4583bf82647ee68b
  85:     0x7fb493fd1a31 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h1418069e8d1c3cc9
  86:     0x7fb493f802a4 - juniper::executor::Executor<CtxT,S>::resolve_into_value_async::{{closure}}::h53d22e7994e34028
  87:     0x7fb493fe2351 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::ha7f357879153b449
  88:     0x7fb493f83b4c - juniper::executor::execute_validated_query_async::{{closure}}::ha5e824a1f0f5e0e2
  89:     0x7fb493fd2751 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h1a74469076f67593
  90:     0x7fb493f58d15 - juniper::execute::{{closure}}::h035e5d450a751b75
  91:     0x7fb493fe6a11 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hdcf64be457bd61db
  92:     0x7fb493efb14f - juniper::http::GraphQLRequest<S>::execute::{{closure}}::h2c5b78920b7fc8f1
  93:     0x7fb493fdfaa1 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h94fd06d493aba587
  94:     0x7fb493efbbeb - juniper::http::GraphQLBatchRequest<S>::execute::{{closure}}::h0618b9598dd2686b
  95:     0x7fb493fdc20f - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h74761df6f1388d6f
  96:     0x7fb493d16c22 - juniper_rocket::GraphQLRequest<S>::execute::{{closure}}::h8d2a6e9d85775c69
  97:     0x7fb493fdb3bb - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h6cbe9031779a6964
  98:     0x7fb494031aa9 - ...::{{closure}}::{{closure}}::h48cd1cb7b8b11f61
  99:     0x7fb493fd6c5b - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h44be78744db5de3c
 100:     0x7fb493fb4455 - <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll::h8cc5c60a4f746620
 101:     0x7fb4940315ba - ...::{{closure}}::hff6208909694c821
 102:     0x7fb493fd04fb - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h085c1a0d9022d01a
 103:     0x7fb494030c00 - ...::{{closure}}::ha73821ef1965a056
 104:     0x7fb493fe899f - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::heed7e2997ffe7b83
 105:     0x7fb49541d39e - <core::pin::Pin<P> as core::future::future::Future>::poll::hc95591857ad2047d
 106:     0x7fb4952d535e - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::future::future::Future>::poll::h120eb1884292cd7a
 107:     0x7fb4952e7371 - <futures_util::future::future::catch_unwind::CatchUnwind<Fut> as core::future::future::Future>::poll::{{closure}}::hececf3c674416752
 108:     0x7fb4952e6f32 - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h6b68352b927dea27
 109:     0x7fb49530dfa4 - std::panicking::try::do_call::h7e3f3fa3d62e5577
 110:     0x7fb49553f53b - __rust_try
 111:     0x7fb49530ce07 - std::panicking::try::h3d04981d9ea481d2
 112:     0x7fb4953092ee - std::panic::catch_unwind::h9513a2de1a371f4e
 113:     0x7fb4952e7184 - <futures_util::future::future::catch_unwind::CatchUnwind<Fut> as core::future::future::Future>::poll::he6cbd009605c472a
 114:     0x7fb4954e3efd - rocket::server::handle::{{closure}}::hde71df61781c63e7
 115:     0x7fb495491c71 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h523bb04e43a7745d
 116:     0x7fb4954ead31 - rocket::server::<impl rocket::rocket::Rocket<rocket::phase::Orbit>>::route::{{closure}}::hc55efb1ac7dbbd94
 117:     0x7fb495495d71 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hd319692d0374de0b
 118:     0x7fb4954e91ac - rocket::server::<impl rocket::rocket::Rocket<rocket::phase::Orbit>>::route_and_process::{{closure}}::hb8180dd8c550cb2d
 119:     0x7fb4954913e3 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h3b789ca4172240cb
 120:     0x7fb4954e8431 - rocket::server::<impl rocket::rocket::Rocket<rocket::phase::Orbit>>::dispatch::{{closure}}::h9dadacf174412077
 121:     0x7fb495496223 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hd5fb6b7ec85e1e05
 122:     0x7fb493ebb145 - rocket::server::hyper_service_fn::{{closure}}::{{closure}}::h6d6822b1ea4c2852
 123:     0x7fb493fd487c - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h2da217b6404b57a2
 124:     0x7fb493ec7eec - <core::pin::Pin<P> as core::future::future::Future>::poll::h5618c1b7cefc864f
 125:     0x7fb493e94166 - tokio::runtime::task::core::CoreStage<T>::poll::{{closure}}::h769d71ca0da51dcf
 126:     0x7fb493e81111 - tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut::h3850227d2801c82f
 127:     0x7fb493e93b72 - tokio::runtime::task::core::CoreStage<T>::poll::h3cac696e86f1fadf
 128:     0x7fb493e9b460 - tokio::runtime::task::harness::poll_future::{{closure}}::h5372daa48444a73e
 129:     0x7fb493c6c2b9 - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h30d88ba03e10f142
 130:     0x7fb493d52687 - std::panicking::try::do_call::h2fc6c8fb404e3a7d
 131:     0x7fb4940c7b3b - __rust_try
 132:     0x7fb493d4f4c8 - std::panicking::try::h0de7c730a8740c38
 133:     0x7fb493d49dad - std::panic::catch_unwind::h2ff65b7a48e2c447
 134:     0x7fb493e9ae73 - tokio::runtime::task::harness::poll_future::heafa78ce2dd893b5
 135:     0x7fb493e9cc4a - tokio::runtime::task::harness::Harness<T,S>::poll_inner::hb97fea7168b4839d
 136:     0x7fb493ea2f83 - tokio::runtime::task::harness::Harness<T,S>::poll::h7b2aaa8e3d909af8
 137:     0x7fb493e8c0a3 - tokio::runtime::task::raw::poll::h0093a9a3b176d643
 138:     0x7fb495a4c5fc - tokio::runtime::task::raw::RawTask::poll::h2f4b49bf94d49d64
 139:     0x7fb495a52eb5 - tokio::runtime::task::LocalNotified<S>::run::hedc2f4642da4d77a
 140:     0x7fb495a6e312 - tokio::runtime::thread_pool::worker::Context::run_task::{{closure}}::hdd48c61195e18032
 141:     0x7fb4959fa298 - tokio::coop::with_budget::{{closure}}::h098a57ab2d1e795f
 142:     0x7fb49596d400 - std::thread::local::LocalKey<T>::try_with::h210aba8d507c423c
 143:     0x7fb49596c8d9 - std::thread::local::LocalKey<T>::with::h7ba254d8c6fef73f
 144:     0x7fb495a6de21 - tokio::runtime::thread_pool::worker::Context::run_task::h4e3ff41c4dac92d1
 145:     0x7fb495a6d6dc - tokio::runtime::thread_pool::worker::Context::run::h02e18eeabf08c90b
 146:     0x7fb495a6d4d9 - tokio::runtime::thread_pool::worker::run::{{closure}}::hcacbffe1e363e6ae
 147:     0x7fb4959effea - tokio::macros::scoped_tls::ScopedKey<T>::set::he99bba38c761eeb1
 148:     0x7fb495a6d428 - tokio::runtime::thread_pool::worker::run::h210bcf02f702cf5d
 149:     0x7fb495a6d257 - tokio::runtime::thread_pool::worker::Launch::launch::{{closure}}::hc427645f6f71b26e
 150:     0x7fb495a5f3f9 - <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll::h9d610d45b519412b
 151:     0x7fb495a2d6c7 - tokio::runtime::task::core::CoreStage<T>::poll::{{closure}}::had6e33e1b8457e5c
 152:     0x7fb4959f8341 - tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut::hd1fd2fc28f6fa3e3
 153:     0x7fb495a2c6b3 - tokio::runtime::task::core::CoreStage<T>::poll::h6f99a3e7146d5278
 154:     0x7fb495a47274 - tokio::runtime::task::harness::poll_future::{{closure}}::h3d6c8826a6a8ceee
 155:     0x7fb495965089 - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::hf15b40a9d7d6eacc
 156:     0x7fb495979a59 - std::panicking::try::do_call::he8f0e8ab167a2dde
 157:     0x7fb495a892eb - __rust_try
 158:     0x7fb495972678 - std::panicking::try::h0dcbcb984eb94797
 159:     0x7fb49596bd3e - std::panic::catch_unwind::hb22532d22742f916
 160:     0x7fb495a45934 - tokio::runtime::task::harness::poll_future::h7fc95e63de943a9d
 161:     0x7fb495a3541c - tokio::runtime::task::harness::Harness<T,S>::poll_inner::h76704a8266b56efe
 162:     0x7fb495a330f4 - tokio::runtime::task::harness::Harness<T,S>::poll::h5da24c1f34439b57
 163:     0x7fb495a4c8b5 - tokio::runtime::task::raw::poll::h54030d10583967d9
 164:     0x7fb495a4c5fc - tokio::runtime::task::raw::RawTask::poll::h2f4b49bf94d49d64
 165:     0x7fb495a52f6a - tokio::runtime::task::UnownedTask<S>::run::h9f9e9aa56052ab19
 166:     0x7fb495a5aca6 - tokio::runtime::blocking::pool::Task::run::h8ddc25853dcd425e
 167:     0x7fb495a5d8d9 - tokio::runtime::blocking::pool::Inner::run::h86242f3e54c4cfbc
 168:     0x7fb495a5ce45 - tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}::h5b83fe11b0a1fe29
 169:     0x7fb495968a80 - std::sys_common::backtrace::__rust_begin_short_backtrace::h398d941c59d708e3
 170:     0x7fb495971fa1 - std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}::h5e2458681e026a98
 171:     0x7fb495964f61 - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::hdb213fbe41137a27
 172:     0x7fb4959795f0 - std::panicking::try::do_call::hcb0fbec52512fb08
 173:     0x7fb495a892eb - __rust_try
 174:     0x7fb49597512f - std::panicking::try::h71bf8a66b327a2ed
 175:     0x7fb49596bb11 - std::panic::catch_unwind::h90a39f2803bf5cf8
 176:     0x7fb495971db3 - std::thread::Builder::spawn_unchecked_::{{closure}}::h7f6cec58cbd1db3a
 177:     0x7fb495988e77 - core::ops::function::FnOnce::call_once{{vtable.shim}}::hb6e694cfa70b6dc2
 178:     0x7fb495d4dd63 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h399961bd3c0bf3e0
                               at /rustc/3c17c84a386e7badf6b2c6018d172496b3a28a04/library/alloc/src/boxed.rs:1853:9
 179:     0x7fb495d4dd63 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h94ad57e4addddc1d
                               at /rustc/3c17c84a386e7badf6b2c6018d172496b3a28a04/library/alloc/src/boxed.rs:1853:9
 180:     0x7fb495d4dd63 - std::sys::unix::thread::Thread::new::thread_start::h755094bd1f1ef1f9
```

**Comment by al8n** [comment]
Thanks @sebasmagri!

**Comment by al8n** [comment]
Fixed by #11
